export type Movie = {
  id: number;
  slug: string;
  title: string;
  originalTitle: string;
  genres: string[];
  year: number;
  episode: number;
  totalEpisodes: number;
  quality: "4K" | "Full HD";
  rating: number;
  views: number;
  duration: number;
  studio: string;
  director: string;
  description: string;
  colors: [string, string];
  featured?: boolean;
  updateDay: string;
  status: "Đang chiếu" | "Hoàn thành" | "Sắp chiếu";
  video: string;
};

const slugify = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
const m = (
  id: number,
  title: string,
  originalTitle: string,
  genres: string[],
  year: number,
  episode: number,
  totalEpisodes: number,
  rating: number,
  views: number,
  colors: [string, string],
  description: string,
  updateDay: string = "Thứ 7",
  status: Movie["status"] = "Đang chiếu",
  featured = false,
): Movie => ({
  id,
  slug: slugify(title),
  title,
  originalTitle,
  genres,
  year,
  episode,
  totalEpisodes,
  quality: id % 5 === 0 ? "Full HD" : "4K",
  rating,
  views,
  duration: 24 + (id % 3) * 3,
  studio: [
    "Tinh Vân Studio",
    "Huyền Quang Animation",
    "Cửu Thiên Pictures",
    "Lam Hải Motion",
  ][id % 4],
  director: ["Lâm Phong", "Tần Mặc", "Hạ Vũ", "Minh Châu"][id % 4],
  description,
  colors,
  featured,
  updateDay,
  status,
  video: "/videos/viufilm3d-demo.mp4",
});

export const genres = [
  "Tất cả",
  "Tiên hiệp",
  "Huyền huyễn",
  "Kiếm hiệp",
  "Xuyên không",
  "Trùng sinh",
  "Cổ trang",
  "Phiêu lưu",
  "Hài hước",
];

export const movieSeed: Movie[] = [
  m(
    1,
    "Thần Vực Cửu Thiên",
    "Nine Heavens Realm",
    ["Tiên hiệp", "Huyền huyễn"],
    2026,
    38,
    52,
    9.6,
    2480000,
    ["#071a35", "#d79235"],
    "Một thiếu niên mang linh mạch bị phong ấn bước qua chín tầng thiên giới để tìm lại ký ức và bảo vệ quê hương.",
    "Thứ 7",
    "Đang chiếu",
    true,
  ),
  m(
    2,
    "Kiếm Tâm Vạn Cổ",
    "Eternal Sword Heart",
    ["Kiếm hiệp", "Cổ trang"],
    2026,
    24,
    36,
    9.3,
    1740000,
    ["#14252f", "#7ea69a"],
    "Kiếm khách trẻ tuổi truy tìm thanh cổ kiếm thất lạc, vô tình vén màn bí mật đã chia cắt võ lâm suốt trăm năm.",
    "Thứ 4",
  ),
  m(
    3,
    "Tinh Hà Nghịch Mệnh",
    "Against the Galaxy",
    ["Huyền huyễn", "Phiêu lưu"],
    2026,
    41,
    60,
    9.5,
    2210000,
    ["#17102f", "#7853d8"],
    "Đội phi hành gia tu luyện băng qua tinh hà đổ vỡ, chiến đấu với thế lực muốn viết lại vận mệnh của muôn loài.",
    "Chủ nhật",
  ),
  m(
    4,
    "Dược Sư Linh Giới",
    "Spirit Realm Alchemist",
    ["Tiên hiệp", "Hài hước"],
    2025,
    52,
    52,
    9.1,
    1390000,
    ["#12392e", "#76b96b"],
    "Một dược sư vụng về sở hữu ngọn lửa kỳ lạ cùng nhóm bạn mở y quán giữa linh giới đầy biến động.",
    "Thứ 2",
    "Hoàn thành",
  ),
  m(
    5,
    "Long Ấn Thức Tỉnh",
    "Awakening Dragon Seal",
    ["Huyền huyễn", "Trùng sinh"],
    2026,
    19,
    40,
    9.4,
    1980000,
    ["#2b1110", "#df693c"],
    "Chiến thần tái sinh trong thân thể phế vật, từng bước đánh thức chín long ấn và đối đầu với quá khứ của chính mình.",
    "Thứ 6",
  ),
  m(
    6,
    "Vân Hải Ký",
    "Chronicles of Cloud Sea",
    ["Tiên hiệp", "Phiêu lưu"],
    2026,
    16,
    30,
    8.9,
    980000,
    ["#0e3443", "#72c7d6"],
    "Hai chị em cưỡi linh điểu vượt biển mây, tìm hòn đảo huyền thoại có thể cứu ngôi làng khỏi mùa đông vĩnh cửu.",
    "Thứ 3",
  ),
  m(
    7,
    "Đế Lộ Vô Song",
    "The Peerless Path",
    ["Huyền huyễn", "Cổ trang"],
    2025,
    64,
    78,
    9.2,
    1870000,
    ["#30200f", "#bc8a43"],
    "Hoàng tử lưu lạc trở về đế đô, dùng trí tuệ và võ đạo phá tan âm mưu của bảy thế gia.",
    "Thứ 5",
  ),
  m(
    8,
    "Thiên Cơ Các",
    "Pavilion of Destiny",
    ["Kiếm hiệp", "Hài hước"],
    2026,
    12,
    24,
    8.8,
    750000,
    ["#2a1533", "#c1729a"],
    "Ba môn đồ tính cách trái ngược cùng điều hành một các bói toán, rồi bị cuốn vào vụ án chấn động kinh thành.",
    "Thứ 7",
  ),
  m(
    9,
    "Hỏa Phượng Niết Bàn",
    "Rebirth of Fire Phoenix",
    ["Trùng sinh", "Tiên hiệp"],
    2026,
    28,
    42,
    9.5,
    2090000,
    ["#391212", "#f05a2a"],
    "Nữ tướng bị phản bội sống lại với huyết mạch hỏa phượng, quyết thay đổi kết cục của vương triều.",
    "Chủ nhật",
  ),
  m(
    10,
    "Kỷ Nguyên Linh Thú",
    "Age of Spirit Beasts",
    ["Huyền huyễn", "Phiêu lưu"],
    2025,
    72,
    80,
    9.0,
    1560000,
    ["#123326", "#c4a951"],
    "Những thiếu niên ngự thú khám phá đại lục hoang dã và học cách chung sống với các linh thú cổ đại.",
    "Thứ 4",
  ),
  m(
    11,
    "Nguyệt Hạ Trường Ca",
    "Ballad Under The Moon",
    ["Cổ trang", "Kiếm hiệp"],
    2026,
    9,
    26,
    8.7,
    610000,
    ["#111c3a", "#9aaee6"],
    "Một khúc đàn giữa đêm trăng dẫn nữ nhạc sư đến hành trình giải mã thân thế của vị tướng quân bí ẩn.",
    "Thứ 2",
  ),
  m(
    12,
    "Vạn Pháp Quy Tông",
    "Origin of All Arts",
    ["Tiên hiệp", "Xuyên không"],
    2026,
    33,
    48,
    9.3,
    1680000,
    ["#18223c", "#5a83bb"],
    "Kỹ sư hiện đại xuyên đến tông môn suy tàn và dùng tư duy khoa học để khôi phục những trận pháp thất truyền.",
    "Thứ 6",
  ),
  m(
    13,
    "Sơn Hà Kiếm Ảnh",
    "Sword Shadow of Mountains",
    ["Kiếm hiệp", "Cổ trang"],
    2025,
    36,
    36,
    8.9,
    1210000,
    ["#243028", "#90a486"],
    "Một bộ khoái về hưu buộc phải cầm kiếm lần nữa khi những bức họa cổ liên tiếp trở thành hiện thực.",
    "Thứ 3",
    "Hoàn thành",
  ),
  m(
    14,
    "Mộng Cảnh Luân Hồi",
    "Dreams of Samsara",
    ["Trùng sinh", "Huyền huyễn"],
    2026,
    21,
    40,
    9.1,
    1430000,
    ["#28183d", "#9c6ac7"],
    "Mỗi lần chìm vào giấc ngủ, cô gái trẻ lại sống một kiếp khác và dần nhận ra mọi giấc mơ đều dẫn tới cùng một kẻ thù.",
    "Thứ 5",
  ),
  m(
    15,
    "Bắc Minh Chi Chủ",
    "Lord of Northern Abyss",
    ["Tiên hiệp", "Huyền huyễn"],
    2025,
    58,
    66,
    9.4,
    1920000,
    ["#071f2d", "#2f84a7"],
    "Người canh giữ Bắc Minh thức tỉnh sau ngàn năm, đối diện thế giới mới nơi lời thề cũ đã bị lãng quên.",
    "Thứ 7",
  ),
  m(
    16,
    "Tiểu Yêu Quái Đi Học",
    "Little Monster Academy",
    ["Hài hước", "Phiêu lưu"],
    2026,
    18,
    30,
    8.8,
    890000,
    ["#264021", "#d6b94b"],
    "Một tiểu yêu nhút nhát nhập học học viện phép thuật và vô tình trở thành người hùng của lớp cá biệt.",
    "Chủ nhật",
  ),
  m(
    17,
    "Cửu Châu Dạ Hành",
    "Night Journey of Nine Realms",
    ["Cổ trang", "Huyền huyễn"],
    2026,
    14,
    32,
    9.0,
    1110000,
    ["#10162c", "#8057a9"],
    "Đoàn áp tiêu chỉ hoạt động về đêm nhận nhiệm vụ đưa chiếc hộp biết nói xuyên qua chín châu.",
    "Thứ 4",
  ),
  m(
    18,
    "Lôi Đình Chiến Ký",
    "Thunder Battle Chronicle",
    ["Huyền huyễn", "Phiêu lưu"],
    2025,
    44,
    50,
    8.9,
    1320000,
    ["#1e2630", "#d4b13f"],
    "Thiếu niên điều khiển lôi điện gia nhập quân đoàn biên cảnh để chống lại cơn bão sống đang nuốt chửng đại lục.",
    "Thứ 2",
  ),
  m(
    19,
    "Hoa Thần Giáng Thế",
    "The Flower Deity",
    ["Tiên hiệp", "Cổ trang"],
    2026,
    11,
    28,
    9.2,
    1270000,
    ["#35182a", "#dc7799"],
    "Hoa thần mất hết thần lực xuống nhân gian, cùng một y sư trẻ chữa lành những vùng đất đang dần hóa đá.",
    "Thứ 6",
  ),
  m(
    20,
    "Học Viện Ngự Kiếm",
    "Swordflight Academy",
    ["Kiếm hiệp", "Hài hước"],
    2026,
    26,
    40,
    8.7,
    1040000,
    ["#152e44", "#69a9cc"],
    "Nhóm học viên đứng cuối bảng sáng tạo cách ngự kiếm khác thường để tham dự đại hội liên minh học viện.",
    "Thứ 3",
  ),
  m(
    21,
    "Ma Đạo Thư Sinh",
    "Scholar of the Arcane",
    ["Xuyên không", "Huyền huyễn"],
    2025,
    40,
    40,
    9.0,
    1490000,
    ["#23142d", "#ad5e70"],
    "Một thủ thư xuyên vào cuốn tiểu thuyết chưa hoàn thành và phải tự viết ra kết thúc để trở về.",
    "Thứ 5",
    "Hoàn thành",
  ),
  m(
    22,
    "Hải Quốc Thiên Ca",
    "Song of the Sea Kingdom",
    ["Phiêu lưu", "Cổ trang"],
    2026,
    17,
    34,
    8.9,
    920000,
    ["#052b3a", "#25a0a5"],
    "Công chúa hải quốc lên đất liền tìm viên ngọc thủy triều, kết giao với đoàn thương nhân kỳ lạ.",
    "Thứ 7",
  ),
  m(
    23,
    "Thợ Săn Tinh Thạch",
    "Crystal Hunters",
    ["Phiêu lưu", "Hài hước"],
    2026,
    13,
    24,
    8.6,
    670000,
    ["#252136", "#e07751"],
    "Bốn thợ săn nghiệp dư rong ruổi qua các di tích nổi để thu thập tinh thạch và trả món nợ khổng lồ.",
    "Chủ nhật",
  ),
  m(
    24,
    "Thiên Môn Thủ Hộ Giả",
    "Guardian of Heaven Gate",
    ["Tiên hiệp", "Kiếm hiệp"],
    2025,
    61,
    72,
    9.3,
    1810000,
    ["#17283a", "#c6d0df"],
    "Người giữ cổng trẻ nhất lịch sử phải lựa chọn giữa luật trời và sinh mệnh của những người dưới hạ giới.",
    "Thứ 4",
  ),
  m(
    25,
    "Cơ Quan Thành",
    "Clockwork City",
    ["Xuyên không", "Phiêu lưu"],
    2026,
    8,
    24,
    8.8,
    580000,
    ["#372714", "#d59a4b"],
    "Nhà phát minh trẻ lạc vào thành phố vận hành bằng cơ quan cổ, nơi thời gian đang chạy ngược.",
    "Thứ 2",
  ),
  m(
    26,
    "Bạch Hồ Vấn Đạo",
    "White Fox Seeks The Way",
    ["Tiên hiệp", "Hài hước"],
    2026,
    22,
    36,
    9.1,
    1180000,
    ["#263146", "#d6d8df"],
    "Bạch hồ tu luyện ngàn năm xuống núi trả ơn nhưng liên tục gây ra những hiểu lầm dở khóc dở cười.",
    "Thứ 6",
  ),
  m(
    27,
    "Thương Lan Quyết",
    "Oath of Azure Waves",
    ["Kiếm hiệp", "Cổ trang"],
    2025,
    32,
    32,
    8.9,
    1340000,
    ["#07343a", "#65b3ac"],
    "Nữ kiếm sư bảo vệ vùng sông nước khỏi bang phái khai thác linh mạch và bí mật gia tộc bị che giấu.",
    "Thứ 3",
    "Hoàn thành",
  ),
  m(
    28,
    "Nhật Ký Ma Tôn",
    "Demon Lord Diary",
    ["Trùng sinh", "Hài hước"],
    2026,
    15,
    30,
    8.7,
    860000,
    ["#2c1422", "#b95368"],
    "Ma tôn tái sinh thành một đứa trẻ, vừa che giấu thân phận vừa cố ngăn thuộc hạ cũ phá hỏng cuộc sống bình yên.",
    "Thứ 5",
  ),
  m(
    29,
    "Cổ Mộ Tinh Không",
    "Tomb Beyond the Stars",
    ["Huyền huyễn", "Phiêu lưu"],
    2026,
    10,
    28,
    9.0,
    990000,
    ["#101b32", "#535fae"],
    "Đoàn khảo cổ bước vào cổ mộ trôi giữa vũ trụ và phát hiện lịch sử của nhân loại từng bị viết lại.",
    "Thứ 7",
  ),
  m(
    30,
    "Phong Khởi Lạc Dương",
    "Wind Rises in Luoyang",
    ["Cổ trang", "Kiếm hiệp"],
    2025,
    46,
    46,
    9.2,
    1590000,
    ["#34220d", "#bb7a38"],
    "Ba nhân vật ở ba tầng lớp cùng điều tra chuỗi vụ mất tích trước lễ hội lớn nhất Lạc Dương.",
    "Chủ nhật",
    "Hoàn thành",
  ),
  m(
    31,
    "Vô Tận Đan Hà",
    "Endless Alchemy River",
    ["Tiên hiệp", "Huyền huyễn"],
    2026,
    7,
    26,
    8.8,
    530000,
    ["#15342e", "#58a377"],
    "Đan sư trẻ xuôi theo dòng sông linh dược để tìm phương thuốc cứu sư phụ và khám phá nguồn gốc của đan hỏa.",
    "Thứ 4",
  ),
  m(
    32,
    "Thiếu Niên Trấn Yêu",
    "Young Demon Warden",
    ["Huyền huyễn", "Hài hước"],
    2026,
    20,
    36,
    8.9,
    960000,
    ["#252d1b", "#97ad4e"],
    "Cậu bé có khả năng nghe tiếng yêu quái trở thành trấn yêu sư bất đắc dĩ của một thị trấn miền núi.",
    "Thứ 2",
  ),
  m(
    33,
    "Kính Hoa Thủy Nguyệt",
    "Mirror Flower, Water Moon",
    ["Cổ trang", "Trùng sinh"],
    2026,
    6,
    24,
    9.0,
    490000,
    ["#271b36", "#b07eb5"],
    "Một chiếc gương cổ đưa nữ họa sư trở lại bảy ngày trước biến cố, nhưng mỗi lần thay đổi quá khứ đều có cái giá riêng.",
    "Thứ 6",
  ),
  m(
    34,
    "Đại Hoang Du Ký",
    "Journey Through the Wilds",
    ["Phiêu lưu", "Huyền huyễn"],
    2025,
    54,
    60,
    9.1,
    1440000,
    ["#2f2a16", "#c9a647"],
    "Nhóm lữ khách đi qua đại hoang, ghi chép các nền văn minh và sinh vật kỳ bí trước khi chúng biến mất.",
    "Thứ 3",
  ),
  m(
    35,
    "Linh Khí Phục Tô",
    "Spiritual Energy Returns",
    ["Xuyên không", "Huyền huyễn"],
    2026,
    0,
    36,
    8.9,
    320000,
    ["#132b32", "#3fc0a4"],
    "Khi linh khí bất ngờ trở lại thành phố hiện đại, một nhóm sinh viên phải học cách bảo vệ cộng đồng bằng năng lực mới.",
    "Thứ 5",
    "Sắp chiếu",
  ),
  m(
    36,
    "Cửu Long Thành Chủ",
    "Lord of Nine Dragons City",
    ["Trùng sinh", "Kiếm hiệp"],
    2026,
    0,
    48,
    9.2,
    410000,
    ["#351b12", "#d4773d"],
    "Thành chủ huyền thoại tỉnh dậy sau ba trăm năm và nhận ra chín tòa thành của mình đã trở thành kẻ thù.",
    "Thứ 7",
    "Sắp chiếu",
  ),
];
